INSERT INTO teams (name, mens, womens)
VALUES ('Pickering FC', true, true),
('BVB IA Waterloo', true, true),
('Woodbridge Strikers', true, true),
('Windsor TFC', true, false),
('Vaughan Azzurri', true, true),
('Unionville Milliken S.C.', true, true),
('St. Catherines Roma', true, true),
('Simcoe County', true, true),
('Sigma FC', true, false),
('Scrosoppi', true, false),
('ProStars FC', true, true),
('Alliance United FC', true, true),
('North Toronto Nitros', true, true),
('North Mississauga SC', true, true),
('Master''s FA', true, false),
('Hamilton United', true, true),
('Guelph United', true, true),
('FC London', true, true),
('Electric City FC', true, true),
('Darby FC', true, true),
('Burlington SC', true, true),
('Blue Devils FC', true, true),
('NDC-Ontario', false, true),
('Tecumseh SC', false, true);